# -*- coding: utf-8 -*-
"""cllg project

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Qp_gM9aDUhJWvQAUZ0qy7MveuDpiHexu
"""



url="https://raw.githubusercontent.com/ankitmisk/PowerBI-Dataset/refs/heads/main/Project_8%20Customer%20Churn%20Analysis%20Report%20-Banking%20Domain/Datasets/CreditCard.xlsx"
credit_card_df = pd.read_excel(url)
print("done")

url = "https://github.com/ankitmisk/PowerBI-Dataset/raw/refs/heads/main/BARCLAYS%20CUSTOMER%20CHURN%20ANALYSIS%20POWERBI%20REPORT/Datasets/ExitCustomer.xlsx"
exit_customer_df = pd.read_excel(url)
print("Done")

url = "https://github.com/ankitmisk/PowerBI-Dataset/raw/refs/heads/main/BARCLAYS%20CUSTOMER%20CHURN%20ANALYSIS%20POWERBI%20REPORT/Datasets/Gender.xlsx"
gender_df = pd.read_excel(url)
print("Done")

url = "https://github.com/ankitmisk/PowerBI-Dataset/raw/refs/heads/main/BARCLAYS%20CUSTOMER%20CHURN%20ANALYSIS%20POWERBI%20REPORT/Datasets/Geography.xlsx"
geography_df = pd.read_excel(url)
print("Done")

url = "https://github.com/ankitmisk/PowerBI-Dataset/raw/refs/heads/main/BARCLAYS%20CUSTOMER%20CHURN%20ANALYSIS%20POWERBI%20REPORT/Datasets/CustomerInfo.csv"
customer_info_df = pd.read_csv(url)
print("Done")

url = "https://github.com/ankitmisk/PowerBI-Dataset/raw/refs/heads/main/BARCLAYS%20CUSTOMER%20CHURN%20ANALYSIS%20POWERBI%20REPORT/Datasets/Bank_Churn.csv"
bank_churn_df = pd.read_csv(url)
print("Done")

all_dfs = [active_customer_df,
           credit_card_df,
           exit_customer_df,
           gender_df,
           geography_df,
           bank_churn_df,
           customer_info_df]

for i in all_dfs:
    print('='*50)
    display(i.sample(2))

# step 3.1: show bank_churn_df sample
bank_churn_df.shape

#14 columns and 10k rows

bank_churn_df.size

# Combine all dfs
merged_df = pd.merge(bank_churn_df, customer_info_df, on='CustomerId')
merged_df = pd.merge(merged_df, geography_df, on='GeographyID')
final_df = pd.merge(merged_df, gender_df, on='GenderID')
final_df

9uurl="https://github.com/ankitmisk/PowerBI-Dataset/raw/refs/heads/main/BARCLAYS%20CUSTOMER%20CHURN%20ANALYSIS%20POWERBI%20REPORT/Datasets/ActiveCustomer.xlsx"
active_customer_df= pd.read_excel(url)
print("Done")

# Step 3.1 Show bank_churn_df Sample
bank_churn_df.sample(5)

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import os
import time
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import confusion_matrix, classification_report
from sklearn.metrics import accuracy_score, recall_score
import pickle
import IPython as ip
from sklearn.ensemble import GradientBoostingClassifier, AdaBoostClassifier
import warnings
warnings.filterwarnings('ignore')
print("All Modules Loaded Successfully!!")

# step 3.2: show df shape size
bank_churn_df.shape
#14 columns and 10k rows

# show column info
# step 3.4
final_df.info()

#step3.5 : Drop Nan or missing values
final_df.dropna(inplace=True)
print("Done")

#step 3.6 : Show data stats
final_df.describe(include = 'number')

#step 3.7 : show categorical data stats
final_df.describe(include = 'object')

#step 3.8 : show data correlation
corr = final_df.corr(numeric_only=True)
corr
#corr range form
#-1 to +1
#-1: represents: Highly -negative correlation
#+1: represents: Highly +positive correlation
#0: represents: no correlation

#step 3.9
plt.figure(figsize = (15,15))
plt.title("Correlation Matrix")
sns.heatmap(corr, annot = True)
plt.show()

#step 3.10 Divide Columns into required objects
textual_columns = final_df.select_dtypes('object').columns
numerical_columns = final_df.select_dtypes('number').columns
print("textual Columns: \n",textual_columns)
print('='*100)
print("Numerical Columns: \n",numerical_columns)

# step 3.11 : Change Bank DOJ to datetime Dtype
final_df['Bank DOJ'] = pd.to_datetime(final_df['Bank DOJ'])
print("Done")

# step 3.12 : Drop unwanted columns
final_df.drop('RowNumber',axis=1,inplace=True)
#axis = 1:means:drop column axis = 0 means:drop row
#inplace=True:means aplly changes in original data set
print("Done")

# 3.13: Univariate Analysis
# means: single columns analysis

plt.figure(figsize = (20,7))

for i, j in enumerate(textual_columns):
    plt.subplot(1,3,i+1)
    temp_df = final_df[j].value_counts().head(20)
    x = temp_df.index
    y = temp_df.values
    plt.title(f"Analysis of {j}")
    ax = plt.bar(x,y, color = sns.color_palette('cool'))
    plt.bar_label(ax)
    plt.xticks(rotation = 90)
    plt.show()

# plt.show: out of loop hai
# subplot: plot multiple plots at once
# i: is index
# j : is column name
# enumerate: to get index and value at same time
# value counts: to grouped data and count its value frequency
# sns.color_palette: to change color shades# 3.13: Univariate Analysis
# means: single columns analysis

plt.figure(figsize = (20,7))

for i, j in enumerate(textual_columns):
    plt.subplot(1,3,i+1)
    temp_df = final_df[j].value_counts().head(20)
    x = temp_df.index
    y = temp_df.values
    plt.title(f"Analysis of {j}")
    ax = plt.bar(x,y, color = sns.color_palette('cool'))
    plt.bar_label(ax)
    plt.xticks(rotation = 90)
    plt.show()

# plt.show: out of loop hai
# subplot: plot multiple plots at once
# i: is index
# j : is column name
# enumerate: to get index and value at same time
# value counts: to grouped data and count its value frequency
# sns.color_palette: to change color shades

# Step 3.15: Create new column for monthly and weekly analysis
final_df['Month'] = final_df['Bank DOJ']. dt. month_name ()
final_df['Day'] = final_df['Bank DOJ'].dt.day_name ( )
# .dt: means: datetime
final_df.sample()

# step 3.16:: Show Monthly Churn Analysis

plt.figure(figsize = (25,8))

plt.title("Month wise churn count")

temp_df = final_df.groupby('Month')['Exited'].sum().sort_values()

x = temp_df.index

y = temp_df.values

ax = plt.bar(x,y,color = sns.color_palette('rainbow'))

plt.bar_label(ax)

plt.xticks(rotation = 90)

plt.show()

# step 3.16:: Show day wise Churn Analysis

plt.figure(figsize = (25,8))

plt.title("Month wise churn count")

temp_df = final_df.groupby('Day')['Exited'].sum().sort_values()

x = temp_df.index

y = temp_df.values

ax = plt.bar(x,y,color = sns.color_palette('mako'))

plt.bar_label(ax)

plt.xticks(rotation = 90)

plt.show()

# step 3.21: Remove unwanted cols for ML model

ml_drop_columns = ['CustomerId', 'GeographyID',

'GenderID', 'Bank DOJ',

'Surname',

'Day']

ml_df = final_df.drop(ml_drop_columns, axis = 1, inplace =

False)

ml_df.sample()

# Step 4.1
import calendar
months_name = list(calendar. month_name) [1:]
index = list(range(len (months_name)))
map = dict(zip(months_name, index))
ml_df['Month'] = ml_df['Month'].map (map)
ml_df.sample()
# zip: bind two object together and give dict
# .map: method to map the key with value

ml_df['GenderCategory'] = ml_df['GenderCategory'].map({'Male': 0, 'Female': 1})

ml_df['GeographyLocation'] = ml_df['GeographyLocation'].map({
    'France': 0,
    'Spain': 1,
    'Germany': 2
})

ml_df.sample()

# Step 4.2 Show target vs feature corr
ml_df.corr()['Exited'].sort_values(ascending=False)

X = ml_df.drop('Exited', axis = 1)

3

y = ml_df['Exited']

4

5

# X: must be capital and in DataFrame

6

#y: must be small and in Series

7

8

print(X.shape)

9

print(y.shape)

# Step 3.14: Bivariate Analysis
# Show Bank DOJ wise churn count

plt.figure(figsize = (25,8))
plt.title("DOJ wise churn count")
temp_df = final_df.groupby('Bank DOJ')['Exited'].sum()
x = temp_df.index
y = temp_df.values
plt.plot(x,y, color = 'r', linestyle = '--')
plt.show()

X_train, X_test, y_train, y_test = train_test_split(X,y,
                                                   random_state=42,
                                                   test_size=0.2)

print("X_train-Shape: ", X_train.shape)
print("X_test-Shape: ", X_test.shape)
print("y_train-Shape: ", y_train.shape)
print("y_test-Shape: ", y_test.shape)

"""BARCLAYS BANKS CHURN ANALYSIS

###project objective
-barclays bank facing high customer churn rate, and customer not keep using services,being a data scientest your task is to identify the companies problem so that they can get the real time insight and management can take decision accordingly ,previously bank were not getting timely insights and did not take decision  timely taht cost high customer churn rate,the previous methodology were old and not upto dated, presently bank needs live analysis and corrective measure to predict the future churn rate and live analysis
"""